name: Atualizar Cambios Diário PowerApps

on:
  schedule:
    - cron: '0 7 * * *'  # Executa todos os dias às 07:00 UTC
  workflow_dispatch:      # Permite executar manualmente

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Obter e processar dados para Power Apps
        run: |
          # Obter JSON original
          curl -s https://api.frankfurter.dev/v1/latest -o latest_raw.json
          
          # Criar JSON simplificado
          jq '[.rates | to_entries[] | {Moeda: .key, Taxa: .value}]' latest_raw.json > latest.json
          jq '[.rates | to_entries[] | {Moeda: .key, Taxa: .value}]' latest_raw.json > latest.txt

      - name: Commit e Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add latest.json
          git commit -m "Atualizar câmbios Power Apps [ci skip]" || echo "Sem alterações"
          git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main


